---
apiVersion: v1
kind: Service
metadata:
  name: kv-store
spec:
  clusterIP: None
  selector:
    app: kv-store
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: kv-store-external
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kv-store-0
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      nodePort: 30051
---